#This does nothing yet, coming in future version :(


##########################################################
#                                                        #    
#                CrucialCommands v1.0                    #  
#                                                        #   
##########################################################

#MOTD Settings
show-on-join: true
MOTD: Welcome to our server!
